LOCAL_PATH := $(my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := uaputl.exe
LOCAL_SRC_FILES := uapcmd.c uaputl.c uaphostcmd.c
LOCAL_MODULE_TAGS := optional

CONFIG_DFS_TESTING_SUPPORT=y
ifeq ($(CONFIG_DFS_TESTING_SUPPORT), y)
LOCAL_CFLAGS += -DDFS_TESTING_SUPPORT
endif

CONFIG_WIFI_DIRECT_SUPPORT=y
ifeq ($(CONFIG_WIFI_DIRECT_SUPPORT), y)
LOCAL_CFLAGS += -DWIFI_DIRECT_SUPPORT
endif

include $(BUILD_EXECUTABLE)
